### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/repo-backend#10]
Como por ahora no funcan bien los servers (pero la api masomenos se puede acceder desde afuera) levanté el frontend en https://huayralinux.github.io/repo-frontend/ pero no anda dado que el repo está levantado en http y github sólo hostea https
¿Existe la posibilidad de barajar un cert aunque sea de letsencrypt?

**Comment by ftoledo** [comment]
Ya funciona http://devel.huayra.conectarigualdad.gob.ar.

El de github dalo de baja ya que no funciona.

Independientemente ni bien podamos vamos a implementar letsencrypt (pero para todo el dominio. No solo para éste host)

**Comment by iglosiggio** [comment]
Genial! Dale
