### ISSUE TITLE
pidfiles

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-backend#7]
La version de start-stop-daemon que tenemos actual en el repo (de wheezy) no soprte make-pidfile ni remove-pidfile (vamos a tener que implementarlo desde el proceso de node).

**Comment by ftoledo** [comment]
Agregué una corrección que saca esos parámetros f5bb2c3522c1e7206bd8089f9c70f35de102d9dc

**Comment by iglosiggio** [comment]
Cierro, se resolvió en f2c2437a6b92d619f69458e18acf9df71c87214e
